TeamManager AS Projekt: TeamManager.Views.Loader.Loaders Class Reference
TeamManager.Views.Loader.Loaders Class Reference
Loaders class used for displaying a loader window without freezing the main thread in a thread safe manner.
Static Public Member Functions
static void StartLoader (LoaderType loader, int sleepMiliseconds=500)
Starts a loader with the specified loader type and the amount in miliseconds to sleep the main thread in order to visualize work.
static void StopLoader (IntPtr windowHandle)
Stops the specified loader thread with the window handle in order to get the parent window to front.
Properties
static Form ParentWindow [get, set]
Sets a reference to the ParentWindow in order to display the loader in the center location of the window.
Static Private Member Functions
static void InvokeLoader (Form window)
Running loader window on a separate thread so the main ui thread will be free when displaying another window.
static void WindowToFront (IntPtr handle)
Brings the window focus using the windows api extern methods.
Static Private Attributes
static readonly ILog Log = Logger.GetLogger()
Logger instance of the class Loaders
static LoaderType _currentLoaderRunning
Tells us which loader is currently running when we want to terminate the thread that runs it.
static LoaderWindow _loaderWindow
The window to display as LoaderType.Loader.
static SplashWindow _splashWindow
The window to display as LoaderType.SplashScreen.
Detailed Description
Loaders class used for displaying a loader window without freezing the main thread in a thread safe manner.
Definition at line 13 of file Loaders.cs.
Member Function Documentation
InvokeLoader()
static void TeamManager.Views.Loader.Loaders.InvokeLoader (Form window) static private
Running loader window on a separate thread so the main ui thread will be free when displaying another window.
Parameters
window
Definition at line 91 of file Loaders.cs.
StartLoader()
static void TeamManager.Views.Loader.Loaders.StartLoader (LoaderType loader, int sleepMiliseconds = 500) static
Starts a loader with the specified loader type and the amount in miliseconds to sleep the main thread in order to visualize work.
Parameters
loader The loader type defined by the LoaderType enum.
sleepMiliseconds When not specified, default will be 500.
Definition at line 39 of file Loaders.cs.
Referenced by TeamManager.Views.Windows.Dialogs.AllPlayersWindow.AllPlayersWindow(), TeamManager.Views.Windows.Dialogs.EditWindow.btnSave_Click(), TeamManager.Views.Windows.MainWindow.MainWindow(), and TeamManager.Views.Windows.Dialogs.UnsignedPlayersWindow.UnsignedPlayersWindow().
StopLoader()
static void TeamManager.Views.Loader.Loaders.StopLoader (IntPtr windowHandle) static
Stops the specified loader thread with the window handle in order to get the parent window to front.
Parameters
windowHandle If you're calling from a Form/Window, pass the Form.Handle property.
Definition at line 64 of file Loaders.cs.
Referenced by TeamManager.Views.Windows.Dialogs.AllPlayersWindow.AllPlayersWindow(), TeamManager.Views.Windows.Dialogs.EditWindow.btnSave_Click(), TeamManager.Views.Windows.MainWindow.MainWindow(), and TeamManager.Views.Windows.Dialogs.UnsignedPlayersWindow.UnsignedPlayersWindow().
WindowToFront()
static void TeamManager.Views.Loader.Loaders.WindowToFront (IntPtr handle) static private
Brings the window focus using the windows api extern methods.
Parameters
handle The handle of the window.
Definition at line 123 of file Loaders.cs.
References TeamManager.Utilities.NativeMethods.SetForegroundWindow().
Member Data Documentation
_currentLoaderRunning
LoaderType TeamManager.Views.Loader.Loaders._currentLoaderRunning static private
Tells us which loader is currently running when we want to terminate the thread that runs it.
Definition at line 19 of file Loaders.cs.
_loaderWindow
LoaderWindow TeamManager.Views.Loader.Loaders._loaderWindow static private
The window to display as LoaderType.Loader.
Definition at line 25 of file Loaders.cs.
_splashWindow
SplashWindow TeamManager.Views.Loader.Loaders._splashWindow static private
The window to display as LoaderType.SplashScreen.
Definition at line 28 of file Loaders.cs.
Log
readonly ILog TeamManager.Views.Loader.Loaders.Log = Logger.GetLogger() static private
Logger instance of the class Loaders
Definition at line 16 of file Loaders.cs.
Property Documentation
ParentWindow
Form TeamManager.Views.Loader.Loaders.ParentWindow static get set
Sets a reference to the ParentWindow in order to display the loader in the center location of the window.
Definition at line 22 of file Loaders.cs.
Referenced by TeamManager.Views.Windows.MainWindow.MainWindow().
The documentation for this class was generated from the following file:
src/TeamManager/Views/Loader/Loaders.cs