TeamManager AS Projekt: TeamManager.Models.Logic.BusinessLogic Class Reference
TeamManager.Models.Logic.BusinessLogic Class Reference
Public Member Functions
BusinessLogic (DatabaseType dbType, SortType sortType)
bool AddNewPlayer (string playerName)
Adds a new Player with a specified playerName.
bool AddNewPlayer (string playerName, string teamId)
Adds a new Player with a specified playerName and teamId.
Team GetPlayerTeam (string teamId)
Retrieves a Team by the specified teamId.
bool AddNewTeam (string teamName)
Adds a new Team with a specified teamName.
bool ChangePlayerName (string playerId, string playerNewName)
Changes a Player name with a specified playerNewName.
bool ChangeTeamName (string teamId, string teamNewName)
Changes a Team name with a specified teamNewName.
List< Player > GetAllPlayers ()
Retrieves all the Players from the database.
List< Player > GetAllPlayers (string filterText, bool ignoreCase)
Retrieves all the Players from the database with a specified filter.
List< Team > GetAllTeams ()
Retrieves all the Teams from the database.
List< Team > GetAllTeams (string filterText, bool ignoreCase)
Retrieves all the Teams from the database with a specified filter.
List< Player > GetTeamPlayers (string teamId)
Retrieves all Team Players with the specified teamId.
List< Player > GetTeamPlayers (string teamId, string filterText, bool ignoreCase)
Retrieves all Team Players with the specified teamId and filter.
bool RemovePlayer (string playerId)
Removes a Player with a specified playerId.
bool RemoveTeam (string teamId)
Removes a Team with a specified teamId.
bool ChangePlayerTeam (string playerId, string teamId)
Changes the Player team with the specified teamId.
Additional Inherited Members
Protected Member Functions inherited from TeamManager.Models.Logic.BusinessLogicBase
BusinessLogicBase (DatabaseType dbType, SortType sortType)
The constructor of the StrategyBase will initialize the database type and receive the type from the constructors of it's inherited objects.
Protected Attributes inherited from TeamManager.Models.Logic.BusinessLogicBase
IDataLayer DbLayer
The IDataLayer instance that will be used for retrieving data from the database.
Static Protected Attributes inherited from TeamManager.Models.Logic.BusinessLogicBase
static ISortStrategy SortBehaviour
Properties inherited from TeamManager.Models.Logic.BusinessLogicBase
static SortType SortType [get, set]
Detailed Description
Definition at line 11 of file BusinessLogic.cs.
Member Function Documentation
AddNewPlayer() [1/2]
bool TeamManager.Models.Logic.BusinessLogic.AddNewPlayer (string playerName)
Adds a new Player with a specified playerName.
Parameters
playerName The Player name.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 16 of file BusinessLogic.cs.
AddNewPlayer() [2/2]
bool TeamManager.Models.Logic.BusinessLogic.AddNewPlayer (string playerName, string teamId)
Adds a new Player with a specified playerName and teamId.
Parameters
playerName The Player name.
teamId The Id of the Team.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 21 of file BusinessLogic.cs.
AddNewTeam()
bool TeamManager.Models.Logic.BusinessLogic.AddNewTeam (string teamName)
Adds a new Team with a specified teamName.
Parameters
teamName The name of the Team.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 31 of file BusinessLogic.cs.
ChangePlayerName()
bool TeamManager.Models.Logic.BusinessLogic.ChangePlayerName (string playerId, string playerNewName)
Changes a Player name with a specified playerNewName.
Parameters
playerId The Id of the Player.
playerNewName The new name of the Player.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 36 of file BusinessLogic.cs.
ChangePlayerTeam()
bool TeamManager.Models.Logic.BusinessLogic.ChangePlayerTeam (string playerId, string teamId)
Changes the Player team with the specified teamId.
Parameters
playerId The Id of the Player.
teamId The Id of the Team.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 95 of file BusinessLogic.cs.
Referenced by TeamManager.Presenters.MainPresenter.DeletePlayer(), and TeamManager.Presenters.MainPresenter.DeleteTeam().
ChangeTeamName()
bool TeamManager.Models.Logic.BusinessLogic.ChangeTeamName (string teamId, string teamNewName)
Changes a Team name with a specified teamNewName.
Parameters
teamId The Id of the Team.
teamNewName The new name of the Team.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 41 of file BusinessLogic.cs.
GetAllPlayers() [1/2]
List<Player> TeamManager.Models.Logic.BusinessLogic.GetAllPlayers ()
Retrieves all the Players from the database.
Returns
Collection of Players.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 46 of file BusinessLogic.cs.
Referenced by TeamManager.Presenters.MainPresenter.Players().
GetAllPlayers() [2/2]
List<Player> TeamManager.Models.Logic.BusinessLogic.GetAllPlayers (string filterText, bool ignoreCase)
Retrieves all the Players from the database with a specified filter.
Parameters
filterText The text to filter when searching for players.
ignoreCase Whether to ignore case sensetive.
Returns
Collection of Players.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 51 of file BusinessLogic.cs.
GetAllTeams() [1/2]
List<Team> TeamManager.Models.Logic.BusinessLogic.GetAllTeams ()
Retrieves all the Teams from the database.
Returns
Collection of Teams.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 59 of file BusinessLogic.cs.
Referenced by TeamManager.Presenters.MainPresenter.Teams().
GetAllTeams() [2/2]
List<Team> TeamManager.Models.Logic.BusinessLogic.GetAllTeams (string filterText, bool ignoreCase)
Retrieves all the Teams from the database with a specified filter.
Parameters
filterText The text to filter when searching for players.
ignoreCase Whether to ignore case sensetive.
Returns
Collection of Teams.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 64 of file BusinessLogic.cs.
GetPlayerTeam()
Team TeamManager.Models.Logic.BusinessLogic.GetPlayerTeam (string teamId)
Retrieves a Team by the specified teamId.
Parameters
teamId The Id of the Team.
Returns
A Team.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 26 of file BusinessLogic.cs.
GetTeamPlayers() [1/2]
List<Player> TeamManager.Models.Logic.BusinessLogic.GetTeamPlayers (string teamId)
Retrieves all Team Players with the specified teamId.
Parameters
teamId The Id of the Team.
Returns
Collection of Players.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 72 of file BusinessLogic.cs.
Referenced by TeamManager.Presenters.MainPresenter.TeamPlayers().
GetTeamPlayers() [2/2]
List<Player> TeamManager.Models.Logic.BusinessLogic.GetTeamPlayers (string teamId, string filterText, bool ignoreCase)
Retrieves all Team Players with the specified teamId and filter.
Parameters
teamId The Id of the Team.
filterText The text to filter when searching for players.
ignoreCase Whether to ignore case sensetive.
Returns
Collection of Players.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 77 of file BusinessLogic.cs.
RemovePlayer()
bool TeamManager.Models.Logic.BusinessLogic.RemovePlayer (string playerId)
Removes a Player with a specified playerId.
Parameters
playerId The Id of the Player.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 85 of file BusinessLogic.cs.
RemoveTeam()
bool TeamManager.Models.Logic.BusinessLogic.RemoveTeam (string teamId)
Removes a Team with a specified teamId.
Parameters
teamId The Id of the Team.
Returns
Whether the operation were successful.
Implements TeamManager.Models.Logic.IBusinessLogic.
Definition at line 90 of file BusinessLogic.cs.
Referenced by TeamManager.Presenters.MainPresenter.DeleteTeam().
The documentation for this class was generated from the following file:
src/TeamManager/Models/Logic/BusinessLogic.cs