TeamManager AS Projekt: TeamManager.Utilities.NativeMethods Class Reference
TeamManager.Utilities.NativeMethods Class Reference
Windows api native methods wrapped into a class with suppress unmanaged code security in order to make the compiler happy.
Package Functions
static bool AllocConsole ()
Allows to allocate console view even if the project configurations set to windows forms as output.
static int FreeConsole ()
Frees console allocation.
static bool SetConsoleCtrlHandler (ConsoleClosedHandler callback, bool add)
Catches the close event chain of the windows api when using console in order to do some wrapping before terminating the application. Note that it can only catch the CTRL_CLOSE(eventType = 2) event when clicking the X button on the right top.
static int SetForegroundWindow (int hWnd)
Brings window focus to the front with the handle of the window.
Detailed Description
Windows api native methods wrapped into a class with suppress unmanaged code security in order to make the compiler happy.
Definition at line 10 of file NativeMethods.cs.
Member Function Documentation
AllocConsole()
static bool TeamManager.Utilities.NativeMethods.AllocConsole () package
Allows to allocate console view even if the project configurations set to windows forms as output.
Returns
Referenced by TeamManager.Program.HookConsole().
FreeConsole()
static int TeamManager.Utilities.NativeMethods.FreeConsole () package
Frees console allocation.
Returns
SetConsoleCtrlHandler()
static bool TeamManager.Utilities.NativeMethods.SetConsoleCtrlHandler (ConsoleClosedHandler callback, bool add) package
Catches the close event chain of the windows api when using console in order to do some wrapping before terminating the application. Note that it can only catch the CTRL_CLOSE(eventType = 2) event when clicking the X button on the right top.
Parameters
callback The method to call when the event occurs.
add Whether to add it to the windows messages api chain or not.
Returns
Referenced by TeamManager.Program.HookConsole().
SetForegroundWindow()
static int TeamManager.Utilities.NativeMethods.SetForegroundWindow (int hWnd) package
Brings window focus to the front with the handle of the window.
Parameters
hWnd
Returns
Referenced by TeamManager.Views.Loader.Loaders.WindowToFront().
The documentation for this class was generated from the following file:
src/TeamManager/Utilities/NativeMethods.cs