TeamManager AS Projekt: TeamManager.Program Class Reference
TeamManager.Program Class Reference
Events
static ConsoleClosedHandler ClosedHandler
Event handler for the console closed event to call the CloseCallback method so it doesn't get garbage collected.
Static Private Member Functions
static void Main (string[] args)
The main father entrance for the application. We can define in the beginning of the application the Strategy(asc, desc, ascMt, descMt), Database type and GUI or TUI. Checks whether the user passed arguments to the console and initialize the application with the wanted data.
static void ValidateConfigurationFile ()
Checks to see whether the configuration file exists, otherwise, create it from stream.
static bool ParseArgs (string[] args)
Parses the arguments that are passed to the executeable and determines whether the parsing operation were successful.
static bool ParseBusinessLogicTypeArg (string arg)
Parses the StrategyType argument for modifying the _strategyType before the main initializes the database and strategy type.
static bool ParseDatabaseTypeArg (string arg)
Parses the DatabaseType argument for modifying the _dbType before the main initializes the database and strategy type.
static bool ParseSortType (string arg)
Parses the SortType argument for modifying the _sortType before the main initializes the IDataLayer and BusinessLogic.
static void HookConsole ()
Hooks the console using the NativeMethods class methods that are exported from the windows api dlls in order to allow the console to show even when the project output type is set to Windows Application, that way we can swap between Gui or Tui. Also registers a callback method with the NativeMethods.SetConsoleCtrlHandler that will register a close event to the console even if someones click the X button on the top right side so we can do last wrapping before console closes.
static bool CloseCallback (int eventType)
Callback method that is registered to the windows kernal with the ConsoleClosedHandler for catching the console close event and doing last wrapping. For more information, please see: https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler
static void PrintHelp ()
Prints the help window to the user with all the configuration options.
static void InvalidSyntax ()
Prints out invalid syntax when invalid syntax received.
Static Private Attributes
static readonly ILog Log = Logger.GetLogger()
Logger instance of the class Program
static readonly Guid SessionId = Guid.NewGuid()
Unique session id of the application.
static bool _startGui = true
The default flag for specifying whether to use Gui or Tui.
static DatabaseType _dbType = Defaults.DatabaseType
The default DatabaseType that is used for initializing the wanted IDataLayer.
static BusinessLogicType _businessLogicType = Defaults.BusinessLogicType
The default StrategyType that is used for initializing the wanted IStrategy.
static SortType _sortType = Defaults.SortType
static readonly List< string > AllowedArgs
The allowed arguments that are acceptable to be pass to the executeable through the console for specifying different configurations.
Detailed Description
Definition at line 17 of file Program.cs.
Member Function Documentation
CloseCallback()
static bool TeamManager.Program.CloseCallback (int eventType) static private
Callback method that is registered to the windows kernal with the ConsoleClosedHandler for catching the console close event and doing last wrapping. For more information, please see: https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler
Parameters
eventType The event type that defines the kind of event that occured when the console application closed.
Returns
Definition at line 247 of file Program.cs.
References TeamManager.Utilities.CtrlType.BREAK, TeamManager.Utilities.CtrlType.C, TeamManager.Utilities.CtrlType.CLOSE, TeamManager.Utilities.CtrlType.LOGOFF, and TeamManager.Utilities.CtrlType.SHUTDOWN.
Referenced by TeamManager.Program.HookConsole(), and TeamManager.Program.Main().
HookConsole()
static void TeamManager.Program.HookConsole () static private
Hooks the console using the NativeMethods class methods that are exported from the windows api dlls in order to allow the console to show even when the project output type is set to Windows Application, that way we can swap between Gui or Tui. Also registers a callback method with the NativeMethods.SetConsoleCtrlHandler that will register a close event to the console even if someones click the X button on the top right side so we can do last wrapping before console closes.
Definition at line 230 of file Program.cs.
References TeamManager.Utilities.NativeMethods.AllocConsole(), TeamManager.Utilities.CtrlType.CLOSE, TeamManager.Program.CloseCallback(), and TeamManager.Utilities.NativeMethods.SetConsoleCtrlHandler().
Referenced by TeamManager.Program.InvalidSyntax(), and TeamManager.Program.ParseArgs().
InvalidSyntax()
static void TeamManager.Program.InvalidSyntax () static private
Prints out invalid syntax when invalid syntax received.
Definition at line 295 of file Program.cs.
References TeamManager.Program.HookConsole().
Referenced by TeamManager.Program.ParseArgs(), TeamManager.Program.ParseBusinessLogicTypeArg(), TeamManager.Program.ParseDatabaseTypeArg(), and TeamManager.Program.ParseSortType().
Main()
static void TeamManager.Program.Main (string [] args) static private
The main father entrance for the application. We can define in the beginning of the application the Strategy(asc, desc, ascMt, descMt), Database type and GUI or TUI. Checks whether the user passed arguments to the console and initialize the application with the wanted data.
Parameters
args The arguements that are being passed to the executeable through the console.
Definition at line 58 of file Program.cs.
References TeamManager.Utilities.CtrlType.CLOSE, TeamManager.Program.CloseCallback(), TeamManager.Program.ParseArgs(), TeamManager.Presenters.BasePresenter.SetStrategyAndDatabaseType(), TeamManager.Views.Tui.Show(), TeamManager.Views.Gui.Show(), and TeamManager.Program.ValidateConfigurationFile().
ParseArgs()
static bool TeamManager.Program.ParseArgs (string [] args) static private
Parses the arguments that are passed to the executeable and determines whether the parsing operation were successful.
Parameters
args The arguments that are passed from the console.
Returns
Returns false if parse failed, true if successful.
Definition at line 101 of file Program.cs.
References TeamManager.Program._startGui, TeamManager.Program.HookConsole(), TeamManager.Program.InvalidSyntax(), TeamManager.Program.ParseBusinessLogicTypeArg(), TeamManager.Program.ParseDatabaseTypeArg(), TeamManager.Program.ParseSortType(), and TeamManager.Program.PrintHelp().
Referenced by TeamManager.Program.Main().
ParseBusinessLogicTypeArg()
static bool TeamManager.Program.ParseBusinessLogicTypeArg (string arg) static private
Parses the StrategyType argument for modifying the _strategyType before the main initializes the database and strategy type.
Parameters
arg The StrategyType argument that is passed from the console.
Returns
Returns false if parse failed, true if successful.
Definition at line 150 of file Program.cs.
References TeamManager.Program.InvalidSyntax().
Referenced by TeamManager.Program.ParseArgs().
ParseDatabaseTypeArg()
static bool TeamManager.Program.ParseDatabaseTypeArg (string arg) static private
Parses the DatabaseType argument for modifying the _dbType before the main initializes the database and strategy type.
Parameters
arg The DatabaseType argument that is passed from the console.
Returns
Returns false if parse failed, true if successful.
Definition at line 176 of file Program.cs.
References TeamManager.Program.InvalidSyntax().
Referenced by TeamManager.Program.ParseArgs().
ParseSortType()
static bool TeamManager.Program.ParseSortType (string arg) static private
Parses the SortType argument for modifying the _sortType before the main initializes the IDataLayer and BusinessLogic.
Parameters
arg The SortType argument that is passed from the console.
Returns
Returns false if parse failed, true if successful.
Definition at line 202 of file Program.cs.
References TeamManager.Program.InvalidSyntax().
Referenced by TeamManager.Program.ParseArgs().
PrintHelp()
static void TeamManager.Program.PrintHelp () static private
Prints the help window to the user with all the configuration options.
Definition at line 260 of file Program.cs.
Referenced by TeamManager.Program.ParseArgs().
ValidateConfigurationFile()
static void TeamManager.Program.ValidateConfigurationFile () static private
Checks to see whether the configuration file exists, otherwise, create it from stream.
Definition at line 89 of file Program.cs.
Referenced by TeamManager.Program.Main().
Member Data Documentation
_businessLogicType
BusinessLogicType TeamManager.Program._businessLogicType = Defaults.BusinessLogicType static private
The default StrategyType that is used for initializing the wanted IStrategy.
Definition at line 35 of file Program.cs.
_dbType
DatabaseType TeamManager.Program._dbType = Defaults.DatabaseType static private
The default DatabaseType that is used for initializing the wanted IDataLayer.
Definition at line 32 of file Program.cs.
_startGui
bool TeamManager.Program._startGui = true static private
The default flag for specifying whether to use Gui or Tui.
Definition at line 29 of file Program.cs.
Referenced by TeamManager.Program.ParseArgs().
AllowedArgs
readonly List<string> TeamManager.Program.AllowedArgs static private
Initial value:
= new List<string>
        {
            "/t", "/g",
            "/b", "/b-mt",
            "/db:mongo", "/db:sql",
            "/s:asc", "/s:dsc",
            "/?", "/h", "--help"
        }
The allowed arguments that are acceptable to be pass to the executeable through the console for specifying different configurations.
Definition at line 40 of file Program.cs.
Log
readonly ILog TeamManager.Program.Log = Logger.GetLogger() static private
Logger instance of the class Program
Definition at line 20 of file Program.cs.
SessionId
readonly Guid TeamManager.Program.SessionId = Guid.NewGuid() static private
Unique session id of the application.
Definition at line 23 of file Program.cs.
Event Documentation
ClosedHandler
ConsoleClosedHandler TeamManager.Program.ClosedHandler static private
Event handler for the console closed event to call the CloseCallback method so it doesn't get garbage collected.
Definition at line 26 of file Program.cs.
The documentation for this class was generated from the following file:
src/TeamManager/Program.cs