TeamManager AS Projekt: TeamManager.Presenters.MainPresenter Class Reference
TeamManager.Presenters.MainPresenter Class Reference
The MainPresenter which will couple together with the Views.Windows.MainWindow and update its view.
Public Member Functions
MainPresenter (IMainView view)
The MainPresenter constructor will receive the IMainView interface from the Views.Windows.MainWindow and couple together with the view. It'll also register a listener to the BasePresenter.ChildClosed event in order to update the view data whenever a child window closes.
void Search (string tbxText, string tbxSearchText, bool searchInTeams)
Filtering functionality in relationship together with IMainView.TeamsListBox and IMainView.PlayersListBox. IMainView.PlayersListBox depends on IMainView.TeamsListBox.
void DeleteTeam ()
Gets the selected Team from the view ListBox and move all their players into unsigned team(id = 0) and deletes the selected Team.
void DeletePlayer ()
Gets the selected Player from the view ListBox and removes it from the current Team to unsigned players team(id = 0).
List< Team > BindTeamsData ()
Gets Teams collection from the Models.Strategy.IStrategy and initialize them to the view. It also changes the TeamSelectedIndex in order to invoke the SelectedIndexChanged in the view which will call also to BindPlayersData to initialize team players into the view.
List< Player > BindPlayersData ()
Gets the selected team Players collection from the Models.Strategy.IStrategy and initialize them to the view. This method gets invoked every time the SelectedIndexChanged of the teams ListBox in the view gets invoked.
Tuple< Team, Player > GetSelectedTeamAndPlayer ()
Gets the selected Team and Player so the view can pass to the Views.Windows.Dialogs.EditWindow in order to edit the selected Player.
Team GetSelectedTeam ()
Gets the selected Team so the view can pass to the Views.Windows.Dialogs.EditWindow in order to create or edit the selected Player or Team.
List< Team > Teams ()
Gets a collection of Teams from the Models.Strategy.IStrategy and checks whether to apply filter or not.
List< Player > Players ()
Gets a collection of Players from the Models.Strategy.IStrategy and checks whether to apply filter or not.
List< Player > TeamPlayers (string teamId)
Gets a collection of Team Players from the Models.Strategy.IStrategy and checks whether to apply filter or not.
override void WindowClosed ()
The MainPresenter not necessarly needs to invoke.
void ChangeStrategy ()
Private Member Functions
void SearchApplyFilter (string tbxText, bool searchInTeams)
Gets the filtered data from the Models.Strategy.IStrategy and updates the view.
void Window_ChildClose (object sender, PresenterArgs args)
Re-bindes teams and players data to the view from the Models.Strategy.IStrategy when a child window closes.
Private Attributes
readonly IMainView _view
The view interface of the Views.Windows.MainWindow which used to update the ui.
bool _allowPlayersDataBinding = true
Flag to temporarily disable SelectedIndexChanged event from updating the view to avoid indexing errors.
string _teamFilterText
Search filter text to search for Teams.
string _playerFilterText
Search filter text to search for Players.
bool _filterTeams
Search filter flag to search for Teams.
bool _filterPlayers
Search filter flag to search for Players.
Static Private Attributes
static readonly ILog Log = Logger.GetLogger()
Logger instance of the class MainPresenter.
Additional Inherited Members
Static Public Member Functions inherited from TeamManager.Presenters.BasePresenter
static void SetStrategyAndDatabaseType (BusinessLogicType blType, DatabaseType dbType, SortType sortType)
Initializes the BusinessLogic with the wanted StrategyType and DatabaseType. Note that this method gets triggered before the view gets initialized in Program.
Protected Member Functions inherited from TeamManager.Presenters.BasePresenter
virtual void OnChildClosed (object sender, PresenterArgs e)
The method that gets called when a child windows wanting to invoke the ChildClosed event in order to notify all other presenters that inherit the BasePresenter.
Static Protected Attributes inherited from TeamManager.Presenters.BasePresenter
static IBusinessLogic BusinessLogic
The IStrategy instance that will be used for retrieving data from the database.
Events inherited from TeamManager.Presenters.BasePresenter
static PresenterHandler ChildClosed
The shared event definition that gets invoked every time a child window is closed.
Detailed Description
The MainPresenter which will couple together with the Views.Windows.MainWindow and update its view.
Definition at line 17 of file MainPresenter.cs.
Constructor & Destructor Documentation
MainPresenter()
TeamManager.Presenters.MainPresenter.MainPresenter (IMainView view)
The MainPresenter constructor will receive the IMainView interface from the Views.Windows.MainWindow and couple together with the view. It'll also register a listener to the BasePresenter.ChildClosed event in order to update the view data whenever a child window closes.
Parameters
view
Definition at line 50 of file MainPresenter.cs.
References TeamManager.Views.Interfaces.IMainView.TeamsListBox.
Member Function Documentation
BindPlayersData()
List<Player> TeamManager.Presenters.MainPresenter.BindPlayersData ()
Gets the selected team Players collection from the Models.Strategy.IStrategy and initialize them to the view. This method gets invoked every time the SelectedIndexChanged of the teams ListBox in the view gets invoked.
Returns
List<Player>
Definition at line 221 of file MainPresenter.cs.
References TeamManager.Models.ResourceData.ResourceBase.Id.
BindTeamsData()
List<Team> TeamManager.Presenters.MainPresenter.BindTeamsData ()
Gets Teams collection from the Models.Strategy.IStrategy and initialize them to the view. It also changes the TeamSelectedIndex in order to invoke the SelectedIndexChanged in the view which will call also to BindPlayersData to initialize team players into the view.
Returns
List<Team>
Definition at line 198 of file MainPresenter.cs.
DeletePlayer()
void TeamManager.Presenters.MainPresenter.DeletePlayer ()
Gets the selected Player from the view ListBox and removes it from the current Team to unsigned players team(id = 0).
Definition at line 172 of file MainPresenter.cs.
References TeamManager.Models.Logic.BusinessLogic.ChangePlayerTeam(), and TeamManager.Models.ResourceData.ResourceBase.Id.
DeleteTeam()
void TeamManager.Presenters.MainPresenter.DeleteTeam ()
Gets the selected Team from the view ListBox and move all their players into unsigned team(id = 0) and deletes the selected Team.
Definition at line 136 of file MainPresenter.cs.
References TeamManager.Models.Logic.BusinessLogic.ChangePlayerTeam(), TeamManager.Models.ResourceData.ResourceBase.Id, and TeamManager.Models.Logic.BusinessLogic.RemoveTeam().
GetSelectedTeam()
Team TeamManager.Presenters.MainPresenter.GetSelectedTeam ()
Gets the selected Team so the view can pass to the Views.Windows.Dialogs.EditWindow in order to create or edit the selected Player or Team.
Returns
Team
Definition at line 263 of file MainPresenter.cs.
GetSelectedTeamAndPlayer()
Tuple<Team, Player> TeamManager.Presenters.MainPresenter.GetSelectedTeamAndPlayer ()
Gets the selected Team and Player so the view can pass to the Views.Windows.Dialogs.EditWindow in order to edit the selected Player.
Returns
Tuple<Team, Player>
Definition at line 245 of file MainPresenter.cs.
Players()
List<Player> TeamManager.Presenters.MainPresenter.Players ()
Gets a collection of Players from the Models.Strategy.IStrategy and checks whether to apply filter or not.
Returns
List<Player>
Definition at line 288 of file MainPresenter.cs.
References TeamManager.Models.Logic.BusinessLogic.GetAllPlayers().
Search()
void TeamManager.Presenters.MainPresenter.Search (string tbxText, string tbxSearchText, bool searchInTeams)
Filtering functionality in relationship together with IMainView.TeamsListBox and IMainView.PlayersListBox. IMainView.PlayersListBox depends on IMainView.TeamsListBox.
Parameters
tbxText The text that the user type in the textbox.
tbxSearchText The text that defined in the designer to show(Search).
searchInTeams To search in teams? If false it will search in players.
Definition at line 67 of file MainPresenter.cs.
SearchApplyFilter()
void TeamManager.Presenters.MainPresenter.SearchApplyFilter (string tbxText, bool searchInTeams) private
Gets the filtered data from the Models.Strategy.IStrategy and updates the view.
Parameters
tbxText
searchInTeams
Definition at line 98 of file MainPresenter.cs.
TeamPlayers()
List<Player> TeamManager.Presenters.MainPresenter.TeamPlayers (string teamId)
Gets a collection of Team Players from the Models.Strategy.IStrategy and checks whether to apply filter or not.
Returns
List<Player>
Definition at line 302 of file MainPresenter.cs.
References TeamManager.Models.Logic.BusinessLogic.GetTeamPlayers().
Teams()
List<Team> TeamManager.Presenters.MainPresenter.Teams ()
Gets a collection of Teams from the Models.Strategy.IStrategy and checks whether to apply filter or not.
Returns
List<Team>
Definition at line 274 of file MainPresenter.cs.
References TeamManager.Models.Logic.BusinessLogic.GetAllTeams().
Window_ChildClose()
void TeamManager.Presenters.MainPresenter.Window_ChildClose (object sender, PresenterArgs args) private
Re-bindes teams and players data to the view from the Models.Strategy.IStrategy when a child window closes.
Parameters
sender
args
Definition at line 317 of file MainPresenter.cs.
WindowClosed()
override void TeamManager.Presenters.MainPresenter.WindowClosed () virtual
The MainPresenter not necessarly needs to invoke.
Implements TeamManager.Presenters.BasePresenter.
Definition at line 335 of file MainPresenter.cs.
References TeamManager.Models.Logic.BusinessLogicBase.SortType.
Member Data Documentation
_allowPlayersDataBinding
bool TeamManager.Presenters.MainPresenter._allowPlayersDataBinding = true private
Flag to temporarily disable SelectedIndexChanged event from updating the view to avoid indexing errors.
Definition at line 26 of file MainPresenter.cs.
_filterPlayers
bool TeamManager.Presenters.MainPresenter._filterPlayers private
Search filter flag to search for Players.
Definition at line 39 of file MainPresenter.cs.
_filterTeams
bool TeamManager.Presenters.MainPresenter._filterTeams private
Search filter flag to search for Teams.
Definition at line 36 of file MainPresenter.cs.
_playerFilterText
string TeamManager.Presenters.MainPresenter._playerFilterText private
Search filter text to search for Players.
Definition at line 33 of file MainPresenter.cs.
_teamFilterText
string TeamManager.Presenters.MainPresenter._teamFilterText private
Search filter text to search for Teams.
Definition at line 30 of file MainPresenter.cs.
_view
readonly IMainView TeamManager.Presenters.MainPresenter._view private
The view interface of the Views.Windows.MainWindow which used to update the ui.
Definition at line 20 of file MainPresenter.cs.
Log
readonly ILog TeamManager.Presenters.MainPresenter.Log = Logger.GetLogger() static private
Logger instance of the class MainPresenter.
Definition at line 23 of file MainPresenter.cs.
The documentation for this class was generated from the following file:
src/TeamManager/Presenters/MainPresenter.cs